# Site settings
title: Rafael Figueira Goncalves
tagline: Rafael Figueira Goncalves
author:
first_button_text: 'Check out some previous projects'
first_button_url: '#portfolio'
header_img: /img/header.jpg
home_menu_text: Rafael Figueira Goncalves
description: Solving Problems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Theme customization
primary: '#004a99'
dark: '#222'

# Contact details
email: clicnet.com.br@gmail.com
telephone_number: 
whatsapp_number: 43998051625
twitter_username: 
github_username: rzfzr
instagram_username: 
facebook_username: 
linkedin_username: 

# Data collections
collections:
  blocks:
    output: false
  gallery:
    output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

